### ISSUE TITLE
Inclusion Requirements

### ISSUE THREAD

**Issue by alecnunn** [vitalysim/Awesome-Hacking-Resources#47]
I was wondering if this resource listing, especially in terms of the tools list, is specific to open source software or if we could include proprietary/closed source software in the listing.

**Comment by vitalysim** [comment]
I think we can include commercial as well and created tags for "open source", "free trial", "commercial paid".
Sounds good?

**Comment by alecnunn** [comment]
Sounds fine to me. I'll work on compiling a list and updating the pages over the next few days.

**Comment by vitalysim** [comment]
You can add a column to each tool and created custom tags using this:
https://shields.io/
I think it will be great

**Comment by white-hat-vaibhs** [comment]
l'amélioration personnelle
