### ISSUE TITLE
Add description to each of the links

### ISSUE THREAD

**Issue by NicolasWebDev** [vitalysim/Awesome-Hacking-Resources#70]
This repository is really nice, but I think that its usefulness would be much improved if there was a really short description accompanying the links.

Right now one has to open all the links and investigate there to know what it is about.

**Comment by vitalysim** [comment]
Noted. It really will be helpful for the community to contribute to that effort.

**Comment by NicolasWebDev** [comment]
I guess that adding one example and a note in the contribution guidelines would make it clear. Indeed the biggest effort should come from the community, but the first step is to make it explicit that short descriptions could be added.

**Comment by dukeofdisaster** [comment]
Started working on adding descriptions to the links, i'd say i'm about a quarter of the way through... also fixing a link or two that pointed the wrong location. Great resource list Vitalysim, thanks for compiling this.

**Comment by dukeofdisaster** [comment]
Just got to the RE section, should complete by tomorrow.

**Comment by vitalysim** [comment]
Thank you @dukeofdisaster for completing the description issue!!!

**Comment by dukeofdisaster** [comment]
My pleasure, glad I could help
