### ISSUE TITLE
Does Awesome-Hacking-Resources have the same usage with https://github.com/wisdomtool/rest-client ?

### ISSUE THREAD

**Issue by wangyudongdom** [vitalysim/Awesome-Hacking-Resources#73]
[Wisdom Tool REST Client ](https://github.com/wisdomtool/rest-client)supports automated testing RESTful API and automatically generating RESTful API documentation.
It's easy to use, just double click the JAR.

Want to know some differences between them.

**Comment by vitalysim** [comment]
No
